spring:
  application:
    name: config-server
#git uri , username , password 
  cloud:
    config:
      server:
        git:
          uri: https://github.com/killeradmin123/Syed-demo-spring
          username: killeradmin123
          password: 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
          clone-on-start: true
          default-label: main
server:
  port: 8888
